### ISSUE TITLE
Can you give me sample to choose location picker that not implemented yet in your feature?

### ISSUE THREAD

**Issue by alek43** [mustfaibra/RoFFu#2]

**Comment by mustfaibra** [comment]
@alek43 Unfortunately, I have no open source project that contain a sample of it, but you can easily implement it with Jetpack Compose GoogleMap composable, check it here 

[Integrate Google Maps into Compose project](https://betterprogramming.pub/integrate-google-maps-into-the-jetpack-compose-app-c2710a226af2)
